# 網站標題
title: Krystal 的桃花源
# 网站标题后缀
suffix: Quiet
# 作者名称
author: Krystal
# 网站关键字
keyword: ""
#false是否开启文章背景图显示(随机图片)
is_article_img: false
# 网站描述
web_description: ""
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: card
# 导航名称
menus_title:
  home: 首頁
  archive: 文章
  categories: 分類
  tags: 標籤
  links: 連結
  about: 關於
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about

# logo
logo: /image/mugShot.jpeg
# header 上logo 一定要用本地存儲
icon: /image/favicon.ico
# 每個頁面展示的圖標和一句話
headers:
  home:
    {
      message: "電腦白痴文組生轉職軟體工程師，帶著各位跟著我一起學習程式教學相長。不務正業的事，如吃喝玩樂都喜歡，希望除了技術也可以分享一些美好事物，讓大家跟我一起不務正業！",
      icon: "/image/mugShot.jpeg",
    }
  archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "目標是至少一個月寫一篇新文章٩(◦`꒳´◦)۶（現在是第 year 年，目前共有 number 篇文章）",
      icon: "/image/kumamon.png",
    }
  tags: { message: "標籤總覽", icon: "/image/kumamon.png" }
  links: { message: "聯絡資訊", icon: "/image/kumamon.png" }
  categories: { message: "文章分類", icon: "/image/kumamon.png" }

# 网页访问统计
web_analytics:
  enable: false #需要改为true
  baidu: 4b5fe1472f22fadsfs # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论
gitalk:
  clientID: 02b3c # （需要替换）GitHub Application Client ID.
  clientSecret: adfc7b4 #（需要替换）GitHub Application Client Secret.
  repo: gimment #（需要替换）GitHub repository.
  owner: duneng #（需要替换）GitHub repository 所有者，可以是个人或者组织。
  admin: ["duneng"] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon:
  #可以多个
  - {
      #描述名称
      name: "Github",
      #图标
      iconLink: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png",
      #跳转链接
      toUrl: "https://github.com/Kkrystalll",
    }
# 友情链接
linksList:
  - {
      title: "GitHub",
      intro: "不能沒有他(,,・ω・,,)",
      link: "https://github.com/Kkrystalll",
      image: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png",
    }
  - {
      title: "Gmail",
      intro: "寄信聯絡我(｡•ㅅ•｡)♡",
      link: "/links",
      image: "https://cdn.cdnlogo.com/logos/g/93/gmail.svg",
    }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php
